### ISSUE TITLE
Link Twitter account to the roast

### ISSUE THREAD

**Issue by 9b** [splitkeycoffee/split-key-roast#3]
Twitter is a good match for roasting where there's a lot of small updates in a brief period of time. Allowing a user to associate their API credentials and specify when to auto-tweet would make the roasting process social.

- [x] Add an integration section to the account dropdown
- [x] Allow users to enable/disable Twitter
- [x] Save the user API credentials
- [x] Allow users to check when to auto-tweet
- [x] Configure events with a decorator to run post-processing
- [x] Execute twitter calls on friendly events
- [x] Test with a live account

**Comment by splitkeycoffee** [comment]
<img width="1535" alt="screen shot 2017-11-26 at 9 41 04 pm" src="https://user-images.githubusercontent.com/33972216/33248427-f31d2822-d2f2-11e7-96b3-85c3d1c70551.png">
